# Generated by Django 5.0.3 on 2024-05-13 21:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sugestao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="O número de telefone deve ser inserido no formato: '+999999999'. Até 10 dígitos permitidos.", regex='^\\+?1?\\d{10}$')])),
                ('sugestao', models.TextField(max_length=200)),
                ('data_sugestao', models.DateTimeField(auto_now_add=True)),
                ('situacao', models.CharField(choices=[('pendente', 'Pendente'), ('avaliada', 'Avaliada')], default='pendente', max_length=20)),
            ],
        ),
    ]
