# Generated by Django 5.0.3 on 2024-04-06 23:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sugestao',
            name='situacao',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('resolvida', 'Resolvida'), ('recusada', 'Recusada')], default='pendente', max_length=20),
        ),
        migrations.AlterField(
            model_name='sugestao',
            name='telefone',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="O número de telefone deve ser inserido no formato: '+999999999'. Até 10 dígitos permitidos.", regex='^\\+?1?\\d{10}$')]),
        ),
    ]
