# Generated by Django 5.0.3 on 2024-03-11 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publico', '0002_alter_sugestao_sugestao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sugestao',
            name='sugestao',
            field=models.TextField(max_length=200),
        ),
    ]
