# Generated by Django 5.0.3 on 2024-03-10 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=100)),
                ('unidade', models.CharField(max_length=20)),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(choices=[('E', 'ENTRADA'), ('S', 'SAÍDA')], max_length=1)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('nome_produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movimentacao.produtos')),
            ],
        ),
    ]
