# Generated by Django 5.0.3 on 2024-03-09 15:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entradas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matricula_colaborador', to='cadastro.colaboradores')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas_produto', to='cadastro.produtos')),
            ],
        ),
    ]
