# Generated by Django 5.0.3 on 2024-03-10 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
        ('movimentacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='colaborador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cadastro.colaboradores'),
        ),
    ]
