# Generated by Django 5.0.3 on 2024-03-10 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
        ('movimentacao', '0002_transacao_colaborador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='colaborador',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cadastro.colaboradores'),
        ),
    ]
