# Generated by Django 5.0.3 on 2024-04-06 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacao', '0002_transacao_saldo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transacao',
            name='saldo',
        ),
    ]
