# Generated by Django 5.0.3 on 2024-04-08 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacao', '0003_remove_transacao_saldo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produtos',
            old_name='nome_produto',
            new_name='nome',
        ),
        migrations.AlterField(
            model_name='produtos',
            name='arrecadacao',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='entradas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='saidas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movimentacao.produtos')),
            ],
        ),
        migrations.DeleteModel(
            name='Transacao',
        ),
    ]
