# Generated by Django 5.0.3 on 2024-04-04 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacao', '0004_rename_saidas_produtos_vendas_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produtos',
            old_name='vendas',
            new_name='saidas',
        ),
    ]
