# Generated by Django 5.0.3 on 2024-04-08 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacao', '0004_rename_nome_produto_produtos_nome_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produtos',
            old_name='entradas',
            new_name='vendas',
        ),
        migrations.RemoveField(
            model_name='produtos',
            name='saidas',
        ),
    ]
