# Generated by Django 5.0.3 on 2024-03-10 19:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colaboradores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('serie', models.CharField(max_length=10)),
                ('data_nascimento', models.DateField()),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('telefone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(max_length=100)),
                ('unidade', models.CharField(max_length=20)),
                ('categoria', models.CharField(max_length=10)),
                ('saldo', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ProdutosVendas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=10)),
                ('unidade', models.CharField(max_length=20)),
                ('saldo', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
